# Generated by Django 4.1.7 on 2023-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T', 'Tv'), ('S', 'SmartPhone'), ('C', 'Clothes'), ('P', 'Pets'), ('O', 'Other')], default=True, max_length=300),
            preserve_default=False,
        ),
    ]
